add controllers v.0
binomay/java-shareit10032023 pull request #1
Opened 2022-12-19 17:56 UTC by binomay

2022-12-20 17:00 UTC, NikolaiDem requested changes

2022-12-20 17:00 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = itemService.getItemById(itemId);
Контроллеры являются граничным слоем, которые работают только с граничными структурами (DTO). Поэтому лучше логику преобразования DTO в модель перенести в сервис.
Аналогично для остальных методов.

2022-12-20 17:00 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Builder
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.
Аналогично для всех DTO и моделей.

2022-12-20 17:00 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +
Лишние пустые строки.

2022-12-20 17:00 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private final String dtoVer = "1.0 спринт 13";
Для чего?

2022-12-20 17:00 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return UserMapper.toUserDto(userService.getUserById(userId));
Контроллеры являются граничным слоем, которые работают только с граничными структурами (DTO). Поэтому лучше логику преобразования DTO в модель перенести в сервис.
Аналогично для остальных методов.

2022-12-20 17:39 UTC, binomay commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private final String dtoVer = "1.0 спринт 13";
Было интересно посмотреть на практике, что Dto могут отличаться от model. забыл грохнуть

2022-12-21 22:51 UTC, NikolaiDem approved these changes

2023-01-13 05:58 UTC, merged