Add bookings
binomay/java-shareit10032023 pull request #2
Opened 2023-01-23 07:22 UTC by binomay

2023-01-24 11:23 UTC, NikolaiDem requested changes

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                  @RequestParam(name = "state", required = false, defaultValue = "ALL") String state) {
required = false избыточно при указании дефолтного значения. Аналогично для остальных кейсов.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public boolean equals(Object o) {
equals(...) и hashCode() с какой целью переопределяются?

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        } else if (booking.getEnd().isBefore(LocalDateTime.now())) {
Если end > start, а start > now, то должно быть end > now. Значит такая проверка лишняя.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
А еще нужно проверить, что новое бронирование не будет пересекаться по времени с уже существующими.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/InputBookingDto.java
> +    //@NotNull(message = "Не указана дата начала бронирования")
Почему удалены проверки?

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(BookingStatus.APPROVED.getName())) {
А если у бронирования статус Rejected?

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/repositary/BookingRepositary.java
> +            "WHERE I.owner_id = ?1 AND B.item_id = I.id AND B.STATUS = ?2 ORDER BY B.START_DATE DESC")
Почему native ? Можно проще написать в объектном стиле:
......AND B.item.owner.id = ?1
Аналогично для остальных запросов.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/repositary/BookingRepositary.java
> +    List<Booking> getCurrenBookingForOwner(Integer ownerId, LocalDateTime date1, LocalDateTime date2);
Current

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private Booking dtoToBooking(InputBookingDto inputBookingDto) {
Очень похоже на метод маппера.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemOutDtoWithDate.java
> +    List<OutputCommentDto> comments;
private?

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/repositary/ItemRepository.java
> +    @Query(nativeQuery = true, value = "SELECT * FROM ITEMS " +
Точно ли нужен native query?
И для следующего запроса тоже.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        ItemOutDtoWithDate outItemDto = new ItemOutDtoWithDate();
Похоже на метод маппера.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return null;
Лучше вернуть пустой список.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            outItemDto.setLastBooking(BookingMapper.toBookDtoForItem(bookingList.get(0)));
Почему заполняется last, а не next ?

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private List<Booking> getLastAndNextBookList(Integer itemId, Integer userId) {
Последнее бронирование таково, что началось в самом ближайшем прошлом. А следующее, которое начнется в самом ближайшем будущем.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemList.stream().map(x -> toItemOutDtoWithDate(x, ownerId)).collect(Collectors.toList());
Проблема N+1 query. Комментарии и last/next бронирования нужно получать из БД одним запросом.

2023-01-24 11:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private OutputCommentDto commentToOutputDto(Comment comment) {
Похоже на метод маппера.

2023-01-24 14:57 UTC, binomay commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public boolean equals(Object o) {
В Теории, да и на QA при работе с Энтити, у которой есть айдишник, советуют сращзу переопределить equels и hashcode, чтобы потом при работе с сетами не было дублей. Я сразу и переопределил. Я сразу и переопределил. Чему-то разве противоречит?:)

2023-01-24 17:51 UTC, binomay commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            outItemDto.setLastBooking(BookingMapper.toBookDtoForItem(bookingList.get(0)));
Логика заполнения списка такова, что если один элемент, то он Last, некст бронирования просто нет

2023-01-24 18:02 UTC, binomay commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private List<Booking> getLastAndNextBookList(Integer itemId, Integer userId) {
Николай, в пачке не могу тебя найти (хотел уточнить). Как с тобой связаться? мой ник @binom_ay
Не спорю, я так и нахожу. сначала отбираю все бронирования для вещи, отсортированные по дате окончания (можно было бы и по дате начала). Потом иду по ним, отбираю бронирование с датой старта до Now (максимальной). Это ласт. Следующее за ней - это некст.

2023-01-24 18:13 UTC, binomay commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemList.stream().map(x -> toItemOutDtoWithDate(x, ownerId)).collect(Collectors.toList());
В Item нет ссылки ни на комментарии, ни на бронирования (manytoone). Можно было бы разместить в item листы бронированиий и комментов (one2many), и потом left join фетчем или энтитиграфом вытащить одним запросом все...  Но в соответствии с ТЗ (рекомендации ментора): Далее доработайте слой сервиса и репозиториев. Здесь есть ещё одна сложность: объект Item не содержит ссылок на  jтносящиеся к нему бронирования... Просто добавить к
существующему запросу получение данных о бронированиях не получится.
Вместо этого добавьте в репозиторий BookingRepository метод, получающий
бронирования для определённой вещи. Booking содержит ссылку на Item , так что
всё получится. Вызовите этот метод внутри сервиса ItemServiceImpl , а затем
вручную добавьте в результирующий DTO-объект нужные данные.....
Отзыв относится к одной вещи, а вот вещь может иметь много комментариев,
поэтому вы будете хранить в Comment ссылку на Item , но в Item ссылок на Comment
Дополнительные советы ментора 5
не будет. Этот пункт аналогичен тому, в котором вы реализовали связь Item —
Booking

2023-01-24 18:15 UTC, binomay commented on src/main/java/ru/practicum/shareit/booking/repositary/BookingRepositary.java
> +            "WHERE I.owner_id = ?1 AND B.item_id = I.id AND B.STATUS = ?2 ORDER BY B.START_DATE DESC")
Переписать в объектном стиле...

2023-01-24 19:25 UTC, binomay commented on src/main/java/ru/practicum/shareit/item/repositary/ItemRepository.java
> +    @Query(nativeQuery = true, value = "SELECT * FROM ITEMS " +
Я предпочел nativequery. Писать длинные по имени методы нет смысла, а объектный запрос - плюс минус тоже самое.

2023-01-27 06:18 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public boolean equals(Object o) {
На будущее
Ответ принят.

2023-01-27 07:13 UTC, NikolaiDem approved these changes

2023-01-27 07:13 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/repositary/BookingRepositary.java
> +            " ((B.start > ?2 AND B.start < ?3) OR (B.end > ?2 AND B.end < ?3)) AND " +
А если совпадают только start и/или end у нового и существующих бронирований?
И лучше проверить статус на равенство APPROVED.

2023-01-27 07:13 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        //букинги отсортированы в порядке возрастания даты начала....
А в методе getItemDtoById(...) они отсортированы по end

2023-01-27 07:13 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    magicBookings.setLastBooking(booking);
Устанавливать значение бронирования N раз, пока оно не превысит текущую дату выглядит излишним.

2023-01-27 07:26 UTC, merged